[server]
port=9002 # Server port
html_root="html-svelte/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable
threads=8

[register] # Register with the server
enable=true # Set to true to publish the server
name="Name"
hardware="SomeSDR"
antenna="Antenna"
description="Description"
url="" # Custom URL, if not server assigns http://ip:port
password="" # Secret ID/password to register, ensures only you can update the details, if left blank a random ID is generated

[limits]
audio=1000
waterfall=1000
events=1000

[input]
sps=20000000 # Input Sample Rate
fft_size=1048576 # FFT bins
brightness_offset=0 # Waterfall brightness offset. Reduce to negative if you see black regions in the waterfall
frequency=98000000 # Baseband frequency
signal="iq" # real or iq
accelerator="none" # Accelerator: none, cuda, opencl
audio_sps=192000 # Audio Sample Rate
audio_compression="flac" # flac or opus
waterfall_size=2048
waterfall_compression="zstd" # zstd or av1


[input.driver]
name="stdin" # Driver name
format="u8" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=93300000 # Default frequency to show user
modulation="WBFM" # Default modulation
