[server]
port=9002 # Server port
html_root="html-svelte/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable
threads=8

[input]
sps=192000 # Input Sample Rate
fft_size=32768 # FFT bins
frequency=7166000 # Baseband frequency
signal="iq" # real or iq
accelerator="none" # Accelerator: none, cuda, opencl
audio_sps=12000 # Audio Sample Rate
waterfall_size=2048

[input.driver]
name="stdin" # Driver name
format="s16" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=7166000 # Default frequency to show user
modulation="USB" # Default modulation
