[server]
port=9002 # Server port
html_root="html-svelte/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable
threads=1
register_online=true # If the SDR should be registered on http://sdr-list.xyz then put it to true
websdr_name="Aachen WebSDR" # Name that is shown on http://sdr-list.xyz
antenna="Mini-Whip" # Antenna that is shown on http://sdr-list.xyz

[limits]
audio=1000
waterfall=1000
events=1000

[input]
sps=64000000 # Input Sample Rate
fft_size=8388608 # FFT bins
fft_threads=4 # FFT threads
frequency=0 # Baseband frequency
signal="real" # real or iq
accelerator="opencl" # Accelerator: none, cuda, opencl
audio_sps=12000 # Audio Sample Rate
audio_compression="flac" # flac or opus
waterfall_size=2048
waterfall_compression="zstd" # zstd or av1


[input.driver]
name="stdin" # Driver name
format="s16" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=5505000 # Default frequency to show user
modulation="USB" # Default modulation
